# Generated by Django 5.0.2 on 2025-09-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_phone_number_patient_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='prn',
            field=models.CharField(default='UNKNOWN-PRN', max_length=32),
        ),
    ]
