# Generated by Django 5.0.2 on 2025-09-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_prn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='prn',
            field=models.CharField(default='UNKNOWN-PRN', max_length=32, unique=True),
        ),
    ]
