# Generated by Django 5.0.2 on 2025-10-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_patient_avatar_remove_patient_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Nonbinary', 'Nonbinary'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], max_length=32, null=True),
        ),
    ]
