# Generated by Django 5.0.2 on 2025-10-02 16:54

import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_patient_prn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='prn',
            field=models.CharField(default=patients.models.generate_prn, editable=False, max_length=8, unique=True),
        ),
    ]
