# Generated by Django 5.2.6 on 2025-11-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_patient_prn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
