services:
  backend:
    build: ./backend
    container_name: healthcare-backend
    command: >
      sh -c "python manage.py migrate &&
         python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: healthcare-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env

volumes:
  postgres_data:
