# Generated by Django 5.2.6 on 2025-11-07 19:35

import schedule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulesettings',
            name='business_hours',
            field=models.JSONField(default=schedule.models.default_business_hours),
        ),
    ]
