# Generated by Django 5.2.6 on 2025-10-24 21:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0008_alter_patient_prn'),
        ('providers', '0002_provider_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(default='Wellness Exam', help_text='Type of appointment (e.g. Wellness Exam, Follow-up, Consultation).', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='chief_complaint',
            field=models.TextField(blank=True, help_text="Brief description of the patient's reason for visit."),
        ),
        migrations.AddField(
            model_name='appointment',
            name='color_code',
            field=models.CharField(default='#FF6B6B', help_text='Color used for this appointment type on the schedule.', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='facility',
            field=models.CharField(choices=[('north', 'North Office'), ('south', 'South Office')], default='north', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='providers.provider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='repeat_days',
            field=models.JSONField(blank=True, help_text="Array of days (e.g. ['Mon', 'Wed', 'Fri']) if recurring.", null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='repeat_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='repeat_interval_weeks',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of weeks between recurring appointments.'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='repeat_occurrences',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Linked patient if this is a patient appointment. Null for block times.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient'),
        ),
    ]
