# Generated by Django 5.2.6 on 2025-10-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_remove_appointment_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='facility',
        ),
        migrations.AddField(
            model_name='appointment',
            name='office',
            field=models.CharField(choices=[('north', 'North Office'), ('south', 'South Office')], default='north', help_text='Which office location this appointment belongs to.', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(default='Wellness Exam', help_text='Type of appointment (e.g., Wellness Exam, Follow-up, Consultation).', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Duration in minutes.'),
        ),
    ]
