# Generated by Django 5.2.6 on 2025-11-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_block',
            field=models.BooleanField(default=False, help_text='True if this record represents a provider block of time.'),
        ),
    ]
