# Generated by Django 5.2.6 on 2025-11-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_is_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='intake_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted')], default='not_submitted', help_text='Intake form status used on the schedule Appointments tab.', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal staff notes visible on the schedule Appointments tab.'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.CharField(blank=True, help_text="Optional room number when status is 'in_room' (e.g. '2' or '309B').", max_length=6),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending arrival'), ('arrived', 'Arrived'), ('in_room', 'In room'), ('no_show', 'No show'), ('cancelled', 'Cancelled'), ('in_lobby', 'In lobby'), ('seen', 'Seen'), ('tentative', 'Tentative')], default='pending', help_text='Workflow status used on the schedule Appointments tab.', max_length=20),
        ),
    ]
