# Generated by Django 5.2.6 on 2025-11-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_intake_status_appointment_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='room',
            field=models.CharField(blank=True, default='', help_text="Optional room number when status is 'in_room' (e.g. '2' or '309B').", max_length=6),
        ),
    ]
