# Generated by Django 5.2.6 on 2025-12-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal staff notes.'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='office',
            field=models.CharField(help_text='Location slug for this appointment (dynamic).', max_length=64),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='repeat_days',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='repeat_interval_weeks',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
