# Generated by Django 5.2.6 on 2025-12-14 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointment_chief_complaint_and_more'),
        ('locations', '0002_seed_locations_from_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Normalized location reference for this appointment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='locations.location'),
        ),
    ]
